### ISSUE TITLE
doesnt launch in my Windows 10 install

### ISSUE THREAD

**Issue by danktankk** [sakakun/Proxmox-Desktop-Client#5]
just starts and disappears..  kinda like a virus would....   :|

I dont see any relevant logs for it either, but I will keep looking around to see if I can find something.

**Comment by sakakun** [comment]
Do you have all the requirements installed.  What version of the software are you running? Version of Windows and WebView2?

I know the previous builds had an issue with the config file not actually being checked and closing.

That all said not pleased about the virus comment, you can scan the installer or exe with what ever software you want before running.  As for the source your more than welcome to build the source code yourself its all there.

**Comment by danktankk** [comment]
I am not home right now.  I did look at your page and noticed a .net dependency.  that is likely the issue.  I will update this when I get back.  thanks for replying!

**Comment by danktankk** [comment]
After getting all the dependencies installed it works pretty well.  Thank you for making this app!  I am excited to see how this one evolves
