### ISSUE TITLE
Adding Server SSL cert.

### ISSUE THREAD

**Issue by TheCount2255** [sakakun/Proxmox-Desktop-Client#6]
Would like there to be a way to add the server's/users public SSL cert to the login screen so that the skipping of SSL check isn't required.
Please let us know how this can be accomplished.

**Comment by sakakun** [comment]
Just so your aware, it isn't skipping SSL connection, the connection is still using SSL just not validating the SSL certificate.  The application still uses standard SSL (HTTPS) connections and if your server has SSL certificates configured correctly then simply use the FQDN of your server and uncheck the box.
